### ISSUE TITLE
Cannot Uninstall and reinstall the Apigee API Catalog module 

### ISSUE THREAD

**Issue by giteshk** [apigee/apigee-api-catalog-drupal#119]
Steps to reproduce:

1. Install Kickstart
2. Uninstall the Apigee API Catalog module.
3. Try to install the Apigee API Catalog module.

Apigee API Catalog module cannot be installed if it's uninstalled.

<img width="1616" alt="image002" src="https://user-images.githubusercontent.com/6208023/105751948-b4d69300-5f6c-11eb-83df-de36d30b842a.png">

**Comment by phdhiren** [comment]
@giteshk,  I could replicate this issue. May be the uninstall is not clean.

**Comment by ssvaidyanathan** [comment]
@phdhiren - Any workarounds?

**Comment by phdhiren** [comment]
@cnovak ,

Few observations while working on this issue

1. Need more cleaner uninstall process - Make sure, apidoc node and taxonomy terms to manually removed by user before actual uninstall, It should be locked otherwise like other core modules.

2. When installing the with kickstart there are additional fields e.g. category and image
However, schema is replicated e.g.
https://github.com/apigee/apigee-api-catalog-drupal/blob/8.x-2.x/config/install/core.entity_form_display.node.apidoc.default.yml
https://github.com/apigee/apigee-devportal-kickstart-drupal/blob/8.x-1.x/config/install/core.entity_form_display.node.apidoc.default.yml

https://github.com/apigee/apigee-devportal-kickstart-drupal/tree/8.x-1.x/config/install
https://github.com/apigee/apigee-api-catalog-drupal/tree/8.x-2.x/config/install

So, when it installed using kickstart version the installation and re-installation schema are conflicting with each other.

3. The entity module is required, if the module is installed independently without other module, but that is not mentioned in dependency.

**Comment by ssvaidyanathan** [comment]
I see the PR tests failed. Can we get this expedited please?

**Comment by cnovak** [comment]
I do not see a submitted PR, where did you see tests failed? 

> I see the PR tests failed. Can we get this expedited please?

**Comment by cnovak** [comment]
@phdhiren is there any workarounds? Any estimate on the work needed to fix?

**Comment by phdhiren** [comment]
@cnovak The initial given fix which is draft is the workaround to install the catalog module (if installed with kickstart).
However, the fix is adding additional fields to original module, which is out of scope for independent module and need to take another path to resolve.

**Comment by phdhiren** [comment]
@giteshk @ssvaidyanathan 

Here is the patch to reinstall the module again with kickstart profile.
Download the file [issue-119.patch.txt](https://github.com/apigee/apigee-api-catalog-drupal/files/6000893/issue-119.patch.txt)
Move the patch to apigee_api_catalog module folder.

Patch can be applied with following command in apigee_api_catalog module folder
`git apply issue-119.patch.txt`

**Comment by phdhiren** [comment]
@giteshk ,

If you would like to have more  more easily one can add additional `patches` section the composer.json  under `extra` section so it look like below

```
      "patches": {
          "drupal/apigee_api_catalog": {
              "#119 Cannot Uninstall and reinstall the Apigee API Catalog module": "https://github.com/apigee/apigee-api-catalog-drupal/files/6000893/issue-119.patch.txt"
          }
      }

```
and then can run `composer update drupal/apigee_api_catalog` to apply patch


More info to apply patch - the composer way at https://www.drupal.org/docs/develop/git/using-git-to-contribute-to-drupal/applying-a-patch-in-a-feature-branch#s-composer

**Comment by codetochangeMinds** [comment]
@phdhiren is there any way to restore the configuration that are lost as part of `apigee_api_catalog` module deletion?
<img width="1788" alt="Screenshot 2021-12-24 at 11 54 15 AM" src="https://user-images.githubusercontent.com/31753232/147324530-338175a5-846c-4b22-ab9e-373bddae5576.png">
