### ISSUE TITLE
Unable to configure MariaDB database on Drupal Kickstart Page in Developer portal.

### ISSUE THREAD

**Issue by satishmsd598** [apigee/apigee-api-catalog-drupal#248]
Hi Drupal team,

We have configured MariaDB in your dev-portal server and updated corresponding details in the Setting.php file.

We have restarted all services. But still we are not able to see MariaDB as a DB option while configuring Dev Portal on Drupal Kickstart Page.

We have followed below document to install developer portal,
https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart/use-kickstart-with-apigee-edge-for-private-cloud

Could you please check and help on this issue, Please schedule call with us to fix this issue.

**Comment by divya-intelli** [comment]
@satishmsd598 ,

Please add a screenshot of what is visible on Drupal kickstart .
Also , add the output of `composer show`.

**Comment by satishmsd598** [comment]
Hi Divya,

We are not seeing any errors in Drupal kickstart web page, our problem is we are not able to see MariaDB as a DB option while configuring Dev Portal on Drupal Kickstart Page. It shows only SQLite DB option in that page. To access OpenAPI secs in developer portal we should configure MariaDB to this Portal.

====================
[root@DC10APGDPTADL11 ~]#
[root@DC10APGDPTADL11 ~]# composer show
-bash: composer: command not found
[root@DC10APGDPTADL11 ~]#
[root@DC10APGDPTADL11 ~]#
========================

Composer was not installed in that server.

**Comment by samuprad** [comment]
composer show
You are running Composer with SSL/TLS protection disabled.
Composer could not detect the root package (apigee/devportal-kickstart-project) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
apigee/apigee-client-php                       2.0.19       Client library for connecting to the Apigee Edge API.
apigee/apigee-mock-client-php                  1.1.1        To be used for queueing mock API responses for the `apigee/apigee-client-php` library.
apigee/apigee_devportal_kickstart              2.1.2        A fast demo and starting point for Apigee Developer Portals.
asm89/stack-cors                               1.3.0        Cross-origin resource sharing library and stack middleware
behat/mink                                     v1.10.0      Browser controller/emulator abstraction for PHP
behat/mink-selenium2-driver                    v1.6.0       Selenium2 (WebDriver) driver for Mink framework
chi-teck/drupal-code-generator                 2.6.2        Drupal code generator
clue/stream-filter                             v1.6.0       A simple and modern approach to stream filtering in PHP
commerceguys/addressing                        v1.4.2       Addressing library powered by CLDR and Google's address data.
commerceguys/intl                              v1.1.2       Internationalization library powered by CLDR data.
composer/ca-bundle                             1.3.5        Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
composer/composer                              2.2.21       Composer helps you declare, manage and install dependencies of PHP projects. It ensures you have the right stack everywhere.
composer/installers                            v1.12.0      A multi-framework Composer library installer
composer/metadata-minifier                     1.0.0        Small utility library that handles metadata minification and expansion.
composer/pcre                                  1.0.1        PCRE wrapping library that offers type-safe preg_* replacements.
composer/semver                                3.3.2        Semver library that offers utilities, version constraint parsing and validation.
composer/spdx-licenses                         1.5.7        SPDX licenses list and validation library.
composer/xdebug-handler                        3.0.3        Restarts a process without Xdebug.
consolidation/annotated-command                4.8.2        Initialize Symfony Console commands from annotated command class methods.
consolidation/config                           2.1.2        Provide configuration services for a commandline tool.
consolidation/filter-via-dot-access-data       2.0.2        This project uses dflydev/dot-access-data to provide simple output filtering for applications built with annotated-command /...
consolidation/log                              2.1.1        Improved Psr-3 / Psr\Log logger based on Symfony Console components.
consolidation/output-formatters                4.2.4        Format text by applying transformations provided by plug-in formatters.
consolidation/robo                             4.0.2        Modern task runner
consolidation/self-update                      2.1.0        Provides a self:update command for Symfony Console applications.
consolidation/site-alias                       3.1.7        Manage alias records for local and remote sites.
consolidation/site-process                     4.2.1        A thin wrapper around the Symfony Process Component that allows applications to use the Site Alias library to specify the ta...
cweagans/composer-patches                      1.7.3        Provides a way to patch Composer packages.
dealerdirect/phpcodesniffer-composer-installer v1.0.0       PHP_CodeSniffer Standards Composer Installer Plugin
dflydev/dot-access-data                        v3.0.2       Given a deep data structure, access data by dot notation.
doctrine/annotations                           1.13.3       Docblock Annotations Parser
doctrine/collections                           1.8.0        PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/deprecations                          v1.0.0       A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all deprecations or select...
doctrine/instantiator                          1.5.0        A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                                 1.2.3        PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/reflection                            1.2.3        The Doctrine Reflection project is a simple library used by the various Doctrine projects which adds some additional functio...
drupal/address                                 1.11.0       Provides functionality for storing, validating and displaying international postal addresses.
drupal/admin_toolbar                           3.3.0        Provides a drop-down menu interface to the core Drupal Toolbar.
drupal/adminimal_admin_toolbar                 1.11.0       Adminimal styling brought to admin toolbar.
drupal/apigee_api_catalog                      3.0.3        Apigee API Catalog for Drupal
drupal/apigee_edge                             2.0.11       Apigee Edge for Drupal.
drupal/apigee_m10n                             2.0.5        Apigee Edge Monetization for Drupal
drupal/better_exposed_filters                  5.2.0        Replaces the Views default single- or multi-select boxes with more advanced options.
drupal/coder                                   8.3.18       Coder is a library to review Drupal code.
drupal/commerce                                2.33.0       Drupal Commerce is a flexible eCommerce solution.
drupal/components                              2.4.0        Registers folders of components defined by your theme or module as Twig namespaces
drupal/core                                    9.5.8        Drupal is an open source content management platform powering millions of websites and applications.
drupal/core-composer-scaffold                  9.5.8        A flexible Composer project scaffold builder.
drupal/core-dev                                9.5.8        require-dev dependencies from drupal/drupal; use in addition to drupal/core-recommended to run tests from drupal/core.
drupal/core-project-message                    9.5.8        Adds a message after Composer installation.
drupal/core-recommended                        9.5.8        Core and its dependencies with known-compatible minor versions. Require this project INSTEAD OF drupal/core.
drupal/ctools                                  4.0.0        Provides a number of utility and helper APIs for Drupal developers and site builders.
drupal/default_content                         1.0.0-alpha9 Imports default content when a module is enabled
drupal/email_registration                      1.2.0        Allows users to register with an email address as their username.
drupal/entity                                  1.4.0        Provides expanded entity APIs, which will be moved to Drupal core one day.
drupal/entity_reference_revisions              1.10.0       Entity Reference Revisions
drupal/file_link                               2.1.0        Extends the core Link module by storing metadata about the target file.
drupal/fontawesome                             2.25.0       The web's most popular icon set and toolkit.
drupal/google_analytics                        3.1.0        Allows your site to be tracked by Google Analytics by adding a Javascript tracking code to every page.
drupal/hal                                     1.0.3        Hypermedia Application Language (HAL)
drupal/inline_entity_form                      1.0.0-rc15   Provides a widget for inline management (creation, modification, removal) of referenced entities.
drupal/jquery_ui                               1.6.0        Provides jQuery UI library.
drupal/jquery_ui_datepicker                    1.4.0        Provides jQuery UI Datepicker library.
drupal/jquery_ui_slider                        1.1.0        Provides jQuery UI Slider library.
drupal/jquery_ui_touch_punch                   1.1.0        Provides jQuery UI Touch Punch library.
drupal/jsonapi_extras                          3.23.0       JSON:API Extras provides a means to override and provide limited configurations to the default zero-configuration implementa...
drupal/key                                     1.17.0       Provides the ability to manage site-wide keys
drupal/paragraphs                              1.15.0       Enables the creation of Paragraphs entities.
drupal/pathauto                                1.10.0       Provides a mechanism for modules to automatically generate aliases for the content they manage.
drupal/profile                                 1.7.0        Provides configurable user profiles.
drupal/radix                                   4.12.0       Radix is a base theme for Drupal. It has Bootstrap, Sass, BrowserSync and Font Awesome built-in.
drupal/requirement                             1.1.0        A Drupal module to that gives modules a way to declare configuration requirement and suggestions.
drupal/smtp                                    1.2.0        Allow for site emails to be sent through an SMTP server of your choice.
drupal/state_machine                           1.7.0        Provides code-driven workflow functionality.
drupal/token                                   1.11.0       Provides a user interface for the Token API, some missing core tokens.
drush/drush                                    11.5.1       Drush is a command line shell and scripting interface for Drupal, a veritable Swiss Army knife designed to make life easier ...
e0ipso/shaper                                  1.2.4        Lightweight library to handle in and out transformations in PHP.
easyrdf/easyrdf                                1.1.1        EasyRdf is a PHP library designed to make it easy to consume and produce RDF.
egulias/email-validator                        3.2.5        A library for validating emails against several RFCs
enlightn/security-checker                      v1.10.0      A PHP dependency vulnerabilities scanner based on the Security Advisories Database.
fightbulc/moment                               1.34         Parse, validate, manipulate, and display dates in PHP w/ i18n support. Inspired by moment.js
firebase/php-jwt                               v6.4.0       A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
friends-of-behat/mink-browserkit-driver        v1.6.1       Symfony2 BrowserKit driver for Mink framework
furf/jquery-ui-touch-punch                     dev-master
grasmash/expander                              2.0.3        Expands internal property references in PHP arrays file.
guzzlehttp/guzzle                              6.5.8        Guzzle is a PHP HTTP client library
guzzlehttp/promises                            1.5.2        Guzzle promises library
guzzlehttp/psr7                                1.9.1        PSR-7 message implementation that also provides common utility methods
instaclick/php-webdriver                       1.4.16       PHP WebDriver for Selenium 2
jeremeamia/superclosure                        2.4.0        Serialize Closure objects, including their context and binding
justinrainbow/json-schema                      5.2.12       A library to validate a json schema.
laminas/laminas-diactoros                      2.14.0       PSR HTTP Message implementations
laminas/laminas-escaper                        2.9.0        Securely and safely escape HTML, HTML attributes, JavaScript, CSS, and URLs
laminas/laminas-feed                           2.17.0       provides functionality for consuming RSS and Atom feeds
laminas/laminas-stdlib                         3.11.0       SPL extensions, array utilities, error handlers, and more
league/container                               4.2.0        A fast and intuitive dependency injection container.
league/period                                  4.12.0       Time range API for PHP
masterminds/html5                              2.7.6        An HTML5 parser and serializer.
mikey179/vfsstream                             v1.6.11      Virtual file system to mock the real file system in unit tests.
myclabs/deep-copy                              1.11.1       Create deep copies (clones) of your objects
nikic/php-parser                               v4.15.4      A PHP parser written in PHP
pear/archive_tar                               1.4.14       Tar file management class with compression support (gzip, bzip2, lzma2)
pear/console_getopt                            v1.4.3       More info available on: http://pear.php.net/package/Console_Getopt
pear/pear-core-minimal                         v1.10.13     Minimal set of PEAR core files to be used as composer dependency
pear/pear_exception                            v1.0.2       The PEAR Exception base class.
phar-io/manifest                               2.0.3        Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                                3.2.1        Library for handling version information and constraints
php-http/client-common                         2.6.1        Common HTTP Client implementations and tools for HTTPlug
php-http/discovery                             1.17.0       Finds and installs PSR-7, PSR-17, PSR-18 and HTTPlug implementations
php-http/guzzle6-adapter                       v2.0.2       Guzzle 6 HTTP Adapter
php-http/httplug                               2.4.0        HTTPlug, the HTTP client abstraction for PHP
php-http/message                               1.14.0       HTTP Message related tools
php-http/message-factory                       1.1.0        Factory interfaces for PSR-7 HTTP Message
php-http/promise                               1.1.0        Promise used for asynchronous HTTP requests
phpdocumentor/reflection-common                2.2.0        Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock              5.3.0        With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is e...
phpdocumentor/type-resolver                    1.7.1        A PSR-5 based resolver of Class names, Types and Structural Element Names
phpmailer/phpmailer                            v6.8.0       PHPMailer is a full-featured email creation and transfer class for PHP
phpspec/prophecy                               v1.17.0      Highly opinionated mocking framework for PHP 5.3+
phpstan/phpdoc-parser                          1.20.3       PHPDoc parser with support for nullable, intersection and generic types
phpunit/php-code-coverage                      9.2.26       Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator                      3.0.6        FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                            3.1.1        Invoke callables with a timeout
phpunit/php-text-template                      2.0.4        Simple template engine.
phpunit/php-timer                              5.0.3        Utility class for timing
phpunit/phpunit                                9.6.7        The PHP Unit Testing framework.
politsin/jquery-ui-touch-punch                 1.0          Extension to jQuery UI for mobile touch event support.
psr/cache                                      1.0.1        Common interface for caching libraries
psr/container                                  1.1.2        Common Container Interface (PHP FIG PSR-11)
psr/http-client                                1.0.2        Common interface for HTTP clients
psr/http-factory                               1.0.2        Common interfaces for PSR-7 HTTP message factories
psr/http-message                               1.0.1        Common interface for HTTP messages
psr/log                                        1.1.4        Common interface for logging libraries
psy/psysh                                      v0.11.16     An interactive shell for modern PHP.
ralouphie/getallheaders                        3.0.3        A polyfill for getallheaders.
react/promise                                  v2.9.0       A lightweight implementation of CommonJS Promises/A for PHP
sebastian/cli-parser                           1.0.1        Library for parsing CLI options
sebastian/code-unit                            1.0.8        Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup             2.0.3        Looks up which function or method a line of code belongs to
sebastian/comparator                           4.0.8        Provides the functionality to compare PHP values for equality
sebastian/complexity                           2.0.2        Library for calculating the complexity of PHP code units
sebastian/diff                                 4.0.4        Diff implementation
sebastian/environment                          5.1.5        Provides functionality to handle HHVM/PHP environments
sebastian/exporter                             4.0.5        Provides the functionality to export PHP variables for visualization
sebastian/global-state                         5.0.5        Snapshotting of global state
sebastian/lines-of-code                        1.0.3        Library for counting the lines of code in PHP source code
sebastian/object-enumerator                    4.0.4        Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector                     2.0.4        Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context                    4.0.5        Provides functionality to recursively process PHP variables
sebastian/resource-operations                  3.0.3        Provides a list of PHP built-in functions that operate on resources
sebastian/type                                 3.2.1        Collection of value objects that represent the types of the PHP type system
sebastian/version                              3.0.2        Library that helps with managing the version number of Git-hosted PHP projects
seld/jsonlint                                  1.9.0        JSON Linter
seld/phar-utils                                1.2.1        PHAR file format utilities, for when PHP phars you up
sirbrillig/phpcs-variable-analysis             v2.11.16     A PHPCS sniff to detect problems with variables.
slevomat/coding-standard                       8.11.1       Slevomat Coding Standard for PHP_CodeSniffer complements Consistence Coding Standard by providing sniffs with additional che...
squizlabs/php_codesniffer                      3.7.2        PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
stack/builder                                  v1.0.6       Builder for stack middleware based on HttpKernelInterface.
symfony-cmf/routing                            2.3.4        Extends the Symfony routing component for dynamic routes and chaining several routers
symfony/browser-kit                            v4.4.44      Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/console                                v4.4.49      Eases the creation of beautiful and testable command line interfaces
symfony/css-selector                           v4.4.44      Converts CSS selectors to XPath expressions
symfony/debug                                  v4.4.44      Provides tools to ease debugging PHP code
symfony/dependency-injection                   v4.4.49      Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts                  v2.5.2       A generic function and convention to trigger deprecation notices
symfony/dom-crawler                            v4.4.45      Eases DOM navigation for HTML and XML documents
symfony/error-handler                          v4.4.44      Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher                       v4.4.44      Provides tools that allow your application components to communicate with each other by dispatching events and listening to ...
symfony/event-dispatcher-contracts             v1.1.13      Generic abstractions related to dispatching event
symfony/filesystem                             v4.4.42      Provides basic utilities for the filesystem
symfony/finder                                 v4.4.44      Finds files and directories via an intuitive fluent interface
symfony/http-client-contracts                  v2.5.2       Generic abstractions related to HTTP clients
symfony/http-foundation                        v4.4.49      Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                            v4.4.50      Provides a structured process for converting a Request into a Response
symfony/inflector                              v5.4.21      Converts words between their singular and plural forms (English only)
symfony/lock                                   v4.4.46      Creates and manages locks, a mechanism to provide exclusive access to a shared resource
symfony/mime                                   v5.4.13      Allows manipulating MIME messages
symfony/options-resolver                       v4.4.44      Provides an improved replacement for the array_replace PHP function
symfony/phpunit-bridge                         v5.4.21      Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-ctype                         v1.27.0      Symfony polyfill for ctype functions
symfony/polyfill-iconv                         v1.27.0      Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme                 v1.27.0      Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn                      v1.27.0      Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer               v1.27.0      Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring                      v1.27.0      Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                         v1.20.0      Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php72                         v1.27.0      Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73                         v1.27.0      Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80                         v1.27.0      Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                                v4.4.44      Executes commands in sub-processes
symfony/property-access                        v4.4.44      Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info                          v4.4.49      Extracts information about PHP class' properties using metadata of popular sources
symfony/psr-http-message-bridge                v2.1.4       PSR HTTP message bridge
symfony/routing                                v4.4.44      Maps an HTTP request to a set of configuration variables
symfony/serializer                             v4.4.47      Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like ...
symfony/service-contracts                      v2.5.2       Generic abstractions related to writing services
symfony/string                                 v5.4.22      Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                            v4.4.47      Provides tools to internationalize your application
symfony/translation-contracts                  v2.5.2       Generic abstractions related to translation
symfony/validator                              v4.4.48      Provides tools to validate values
symfony/var-dumper                             v5.4.22      Provides mechanisms for walking through any arbitrary PHP variable
symfony/yaml                                   v4.4.45      Loads and dumps YAML files
theseer/tokenizer                              1.2.1        A small library for converting tokenized PHP source code into XML and potentially other formats
twig/twig                                      v2.15.4      Twig, the flexible, fast, and secure template language for PHP
typo3/phar-stream-wrapper                      v3.1.7       Interceptors for PHP's native phar:// stream handling
webflo/drupal-finder                           1.2.2        Helper class to locate a Drupal installation from a given path.
webmozart/assert                               1.11.0       Assertions to validate method input/output with nice error messages.
webmozart/path-util                            2.3.0        A robust cross-platform utility for normalizing, comparing and modifying file paths.
webonyx/graphql-php                            v14.11.9     A PHP port of GraphQL reference implementation

**Comment by samuprad** [comment]
let us know why we are not able to see mariadb or postgressql as an option.

**Comment by samuprad** [comment]
![image](https://github.com/apigee/apigee-api-catalog-drupal/assets/68565223/23d35ac1-7f26-4f73-b2fd-93c4b4ab58c2)

**Comment by kedarkhaire** [comment]
Hi @satishmsd598 & @samuprad 
Thanks for sharing the details.

Please check if the Mariadb server status via terminal. _(If not enabled, please enable it or if not installed, please install it on your host)_

The Database type field lists only those options which is supported and enabled in your host, it has nothing to do with the API catlog module as it is a Drupal's functionality.

Also we looked to your above messages, seems you had only updated the drupal core and not the contributed modules & theme.

Please update all the modules and themes to their latest versions to avoid any further issues.

Thanks!

**Comment by samuprad** [comment]
We  have installed it in the same host, and enabled it.

**Comment by samuprad** [comment]
@divya-intelli  and @kedarkhaire

**Comment by kedarkhaire** [comment]
Hi @samuprad 

php-mysql & php-mysqlnd these are the 2 main important php libraries which are required by Mariadb when accessing it with PHP, make sure those are also installed with php.

The above-mentioned issue/request is not related to the Apigee Api Catlog drupal module, i request you to please check with your host setup team as this issue is with your host, where few dependencies are not resolved and that's why you are facing the issues with the setup.

Thanks!

**Comment by satishmsd598** [comment]
Hi @kedarkhaire,

We have installed "php-mysql & php-mysqlnd" these two required packages and configured MariaDB to this dev portal, we can see the below home page.

But after that we are getting 403 error in web page while accessing dev portal. Please find below nginx error logs.


And please check below php-fpm error logs also.

tail -100 error.log-20240324
[17-Mar-2024 03:29:01] NOTICE: error log file re-opened
[22-Mar-2024 09:56:02] NOTICE: Terminating ...
[22-Mar-2024 09:56:02] NOTICE: exiting, bye-bye!
[22-Mar-2024 09:56:03] NOTICE: fpm is running, pid 3079317
[22-Mar-2024 09:56:03] NOTICE: ready to handle connections
[22-Mar-2024 09:56:03] NOTICE: systemd monitor interval set to 10000ms
[22-Mar-2024 10:26:59] NOTICE: Terminating ...
[22-Mar-2024 10:26:59] NOTICE: exiting, bye-bye!
[22-Mar-2024 10:26:59] NOTICE: fpm is running, pid 3122462
[22-Mar-2024 10:26:59] NOTICE: ready to handle connections
[22-Mar-2024 10:26:59] NOTICE: systemd monitor interval set to 10000ms
[22-Mar-2024 10:29:27] NOTICE: Terminating ...
[22-Mar-2024 10:29:27] NOTICE: exiting, bye-bye!
[22-Mar-2024 10:31:24] NOTICE: fpm is running, pid 982
[22-Mar-2024 10:31:24] NOTICE: ready to handle connections
[22-Mar-2024 10:31:24] NOTICE: systemd monitor interval set to 10000ms
[22-Mar-2024 10:57:41] NOTICE: Terminating ...
[22-Mar-2024 10:57:41] NOTICE: exiting, bye-bye!
[22-Mar-2024 10:57:41] NOTICE: fpm is running, pid 31497
[22-Mar-2024 10:57:41] NOTICE: ready to handle connections
[22-Mar-2024 10:57:41] NOTICE: systemd monitor interval set to 10000ms
[22-Mar-2024 11:26:48] NOTICE: Terminating ...
[22-Mar-2024 11:26:48] NOTICE: exiting, bye-bye!
[22-Mar-2024 11:26:48] NOTICE: fpm is running, pid 57884
[22-Mar-2024 11:26:48] NOTICE: ready to handle connections
[22-Mar-2024 11:26:48] NOTICE: systemd monitor interval set to 10000ms
[22-Mar-2024 11:33:55] NOTICE: Terminating ...
[22-Mar-2024 11:33:55] NOTICE: exiting, bye-bye!
[22-Mar-2024 11:33:55] NOTICE: fpm is running, pid 60962
[22-Mar-2024 11:33:55] NOTICE: ready to handle connections
[22-Mar-2024 11:33:55] NOTICE: systemd monitor interval set to 10000ms
[22-Mar-2024 11:40:42] NOTICE: Terminating ...
[22-Mar-2024 11:40:42] NOTICE: exiting, bye-bye!
[22-Mar-2024 11:40:42] NOTICE: fpm is running, pid 66454
[22-Mar-2024 11:40:42] NOTICE: ready to handle connections
[22-Mar-2024 11:40:42] NOTICE: systemd monitor interval set to 10000ms

**Comment by kedarkhaire** [comment]
Hi @satishmsd598 

Here we see that your main issue of _MariaDB not configurable_ is solved and seems you have successfully installed the drupal setup also.

For the 403 errors, you may lack sufficient permissions in your hosts for the files or might have any mis-configuration in .htaccess file related to your setup. Please solve those permission/htaccess issues it will help to solve the others. 

These issues are related to your host and not related to the Apigee Api Catlog Drupal module, i request you to please check with your host setup team as this 403 issue is with your host.

Also, please try to avoid posting private details like host, env. details and other PII data like email id and etc, I have removed that data from your previous comment for better privacy practices.

Thanks!

**Comment by kedarkhaire** [comment]
Hi @satishmsd598 

As per your logs shared this is the issue in your nginx config file -  **_duplicate location "/" in /../../nginx.conf:77_**

Please make sure that the nginx.conf file code is similar to [this source code](https://www.nginx.com/resources/wiki/start/topics/recipes/drupal/) 

Do clear your caches post that and check the site after the change. For any queries regarding it, do follow [this document](https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart/use-kickstart-with-apigee-edge-for-private-cloud).

Thanks!

**Comment by pradeep-developer** [comment]
Thanks for the input.
After that it worked and went to home screen, but it shows this error after we clicked on available security updates to update to 10.2.4 

dependencyInjection/Container.php on line 259 and exactly 4 expected in /

**Comment by pradeep-developer** [comment]
![Screenshot_28-3-2024_02123_dc10apgdptadl11 molina mhc](https://github.com/apigee/apigee-api-catalog-drupal/assets/24683348/028d2a9b-0878-4495-8de8-95ff8f9aac72)

**Comment by pradeep-developer** [comment]
How do we get out of maintance mode without loggin in.

**Comment by kedarkhaire** [comment]
Hi @pradeep-developer 

The logs which you shared consists of the server IP, your environment address also the webpath is visible, please do not share such details here for security reasons, do edit and remove the said data from above comments.

Regarding the issues,

1. After checking the logs, Seems you are having issues with the Admin toolbar contrib module, try uninstalling it and check.
2. Use drush command from [here](https://www.drupal.org/docs/user_guide/en/extend-maintenance.html#s-enabling-or-disabling-maintenance-mode-using-drush) to disable the maintenance mode without logging in.
3. Do not directly migrate to 10.2.4 version of Drupal, our modules are not yet compatible with the latest version, we are working on it for its compatibility, please use Drupal 10.1 to avoid any issues.

Thanks!

**Comment by kedarkhaire** [comment]
Hi @pradeep-developer Hi @satishmsd598 
Its been more than 2 weeks there is no response, considering, last comment helped you to solve the said issues.
Closing this ticket for now. 
Thanks!
