### ISSUE TITLE
"Page not found" when trying to access API documentation

### ISSUE THREAD

**Issue by d1ndra** [apigee/apigee-api-catalog-drupal#32]
**Describe the bug**
API documentation doesn't show, instead says "Page not found"

**To Reproduce**
1. Go to home page / API list page
2. Click on any catalog
3. "Page not found"

**Expected behavior**
List of APIs

**Screenshots**
.
![image](https://user-images.githubusercontent.com/7220131/59040094-a4ebd600-8893-11e9-8aff-1c8f278b2d73.png)

**Version Info**
1.1.0 of apigee-devportal-kickstart-drupal

**Comment by cnovak** [comment]
Thanks for the info @d1ndra, that helps explain the problem.  

The SmartDocs module [gets the URL for the spec in public filesystem](https://github.com/apigee/apigee-api-catalog-drupal/blob/8.x-1.x/src/Plugin/Field/FieldFormatter/SmartDocsFormatter.php#L126), which will either be the `file_public_base_url` setting in your [settings.php file](https://api.drupal.org/api/drupal/sites%21default%21default.settings.php/8.7.x) or will use the base URL of the site.  

You should not have to set the file_public_base_url however unless your public files are not in a default place.  The base url is determined by the HTTP host header or the [PHP $_SERVER vars](https://php.net/reserved.variables.server) which should be set by your web server. 

Are you sure you have configured your web server properly? There are many tutorials on the web, or you can look at [instructions on how to host the site on your local machine](https://www.drupal.org/docs/develop/local-server-setup).  It could also be that your web server is defaulting back to the server's host name, which is localhost because it is not set?

It looks like you installed Drupal CMS in s subdirectory which may be causing you issues. The path to the file from your configuration is `http://<machine-name.domain>/drupal8-devportal/web/sites/default/files/apidoc_specs/petstore.yaml`, but it should be `http://<machine-name.domain>/sites/default/files/apidoc_specs/petstore.yaml` if Drupal is in your web server's document root.  I think you did not set your webroot properly.   If you are using Apache, make sure to set the DocumentRoot in Apache's httpd.conf to the path of your Drupal directory.  If you are using Nginx, check out the [Nginx configuration for Drupal](https://www.nginx.com/resources/wiki/start/topics/recipes/drupal/). You can see the Nginx configuration sets `root` to be the place Drupal is installed on the server.

Will close issue for now, but reopen if you have any more questions.
