### ISSUE TITLE
'Try it Now' Functionality not OAuth Compliant

### ISSUE THREAD

**Issue by m-khan23** [apigee/apigee-api-catalog-drupal#62]
When making an OAuth (clientCredentials) call, the Authorization token that is placed by this module is 'bearer <TOKEN>'. The OAuth compliant version is 'Bearer <TOKEN>'.  This breaks interaction with the default out of Edge. This either needs to be fixed or there needs to be an option to change the prefix on the Portal side.

**Comment by cnovak** [comment]
@m-khan23 , is this issue about the Apigee OAuth policy not sending back the proper `token_type` attribute? The Apigee Edge OAuth policy sends "token_type":"BearerToken" instead of "token_type":"Bearer" as described in the [Apigee OAuth policy documentation section on Non RFC compliant behavior](https://docs.apigee.com/api-platform/reference/policies/oauthv2-policy#non-rfc-compliant-behavior).  That section also gives links to solutions for this.

Let us know if this solves your issue or you have a different problem.

**Comment by m-khan23** [comment]
Hey @cnovak,

That's not quite it. When trying the 'Try it now' Functionality using this module, the module will attempt to make a call to edge with the header as 'Authorization: bearer <AUTH TOKEN>' (tested with an endpoint requiring OAuth Client Credentials).

However, that will not work - even with Edge out of the box. OAuth policy expects the header as:

'Authorization: Bearer <AUTH TOKEN>'

With a capital 'B'.

The issue you described is earlier in the process (when requesting an access token, not when using the access token) and is a separate issue that we have mitigated. Thanks for the help!

**Comment by cnovak** [comment]
@m-khan23 The `Authorization` header "bearer" value is being sent by SmartDocs as whatever response value was sent back in the `token_type` attribute the when the client was making a token access request. This is the same way Swagger UI works, you can try this in that UI to see same issue.

This is a bit hard to explain, so I will go through an example flow:

1. Developer clicks on "Authorize" in SmartDocs
2. SmartDocs displays form for developer asking for "Client ID" and "Secret'
3. Developer fills in "Client ID" and "Secret', hits "Authorize" button.
4. Browser sends request to get token to Edge
5. Edge validates and returns a response that contains token, along with an attribute named "token_type".  I believe in your situation the value coming back is `bearer`.
6. Developer goes back to  API they wanted to try, clicks "Execute".
7. Browser sends request with "Authorization" header with the value of "token_type" as the authorization scheme. In our example of "token_type" being set to `bearer`, the "Authorization" header  will be set to `bearer t123`, where the token value is `t123`.

This situation also comes up when using the Apigee OAuth 2.0 policy, since the default behavior in step 5 is to send back a "token_type" of value `BearerToken`. To fix either issue, modify your proxy by adding a JavaScript policy in the post flow after the OAuth policy:

```
// Change "token_type" in JSON response from "BearerToken" to
// "Bearer" to be RFC compliant.
// https://docs.apigee.com/api-platform/reference/policies/oauthv2-policy#non-rfc-compliant-behavior
var obj = JSON.parse(response.content);
obj.token_type = "Bearer";
context.setVariable('response.content', JSON.stringify(obj));
``` 

## Resources

- [Apigee OAuth 2.0 Policy Non RFC complaint behavior](https://docs.apigee.com/api-platform/reference/policies/oauthv2-policy#non-rfc-compliant-behavior)
- [Apigee Community article on using JavaScript to fix "token_type"](https://community.apigee.com/answers/51535/view.html)

**Comment by cnovak** [comment]
I will close this issue, but comment again if this is still an issue.
