### ISSUE TITLE
API Catalog page - IE 11 issue

### ISSUE THREAD

**Issue by gautam-dac** [apigee/apigee-api-catalog-drupal#69]
The API catalog page works fine in all browsers, BUT IE - 11

It gives an error : 

SCRIPT1002: Syntax error
vendor.js (1, 874841)

Can anyone provide any inputs on this please.

**Comment by arunz6161** [comment]
@gautam-dac could you please provide us with a screenshot of the page and the url?

**Comment by SajithAthukorala** [comment]
@arunz6161 
getting same issue on page     example.com/api/3  page , api specification does not load, page remains with text  "loading"

![image(2)](https://user-images.githubusercontent.com/7125840/80593029-10a3d800-8a3e-11ea-8886-8cfe04971470.png)

**Comment by jacine** [comment]
I spent some time looking into this today, and I was able to reproduce this in a Kickstart install, with some of the same errors as @SajithAthukorala. There are 2 different errors happening:

1. The `cssVars()` error, which appears to be CORS related. It's coming from https://github.com/jhildenbiddle/css-vars-ponyfill, which we use in the Kickstart project to polyfill CSS variables. It's failing to read https://www.gstatic.com/smartdocs/1.1.0/styles.css which it tries to do, in order to polyfill any CSS variables that might be present. There are no CSS variables we need to work with in SmartDocs, so we *can* prevent it from running on that file. This would allow us resolve a few of those errors, but it doesn't appear that these errors are actually breaking anything. I was able to confirm this by [allowing it to run in Chrome](https://github.com/jhildenbiddle/css-vars-ponyfill/issues/62#issuecomment-472312307), where the same exact errors were present, and where SmartDocs is still loading properly.

2. There is an error happening in https://www.gstatic.com/smartdocs/1.1.0/vendor.js, which is actually preventing the SmartDocs from loading. The line in question is`Object.assign(r,...Object.keys(t).map` (IE doesn't support spread syntax).

    ```
    SCRIPT1002: Syntax error
    vendor.js (1,874841)
    ```

    This appears to be the `return` in this block of code:

    ```js
    circularClone: function e(t, n) {
      /// [more code snipped]
      // IE11 Fails right at the spread syntax: '...Object'.
      return n.set(t, r), Object.assign(r, ...Object.keys(t).map(r => ({
        [r]: e(t[r], n)
      })))
    }
    ```

    I'm also not seeing a [polyfills.js](https://www.gstatic.com/smartdocs/1.1.0/polyfills.js) error, like in the screenshot above.

---

Here are some screenshots of the errors on my local.

Loading any api doc page, e.g. `/api/3` looks like:

<img width="1511" alt="error" src="https://user-images.githubusercontent.com/60979/84431804-ee36da00-abf9-11ea-95bc-91b2bdee9d4c.png">

If I prevent the CSS vars polyfill from running on the SmartDocs CSS (to prevent the CORS issue), I have less errors, but I still have the above vendor.js error, and a broken SmartDocs page.

<img width="1511" alt="error-after-excluding" src="https://user-images.githubusercontent.com/60979/84431968-276f4a00-abfa-11ea-8673-e2c05d422f04.png">

**Comment by cnovak** [comment]
It sounds like this may be an issue with running SmartDocs on IE 11, will find out if IE 11 is supported.

**Comment by cnovak** [comment]
Talking to the SmartDocs team, they pointed out that they do not run tests against IE 11. Here are the browsers supported: https://docs.apigee.com/release/supported-software#browsers
