### ISSUE TITLE
Enabling JSON API modules results in WSOD

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-api-catalog-drupal#83]
**Describe the bug**
As soon as we enable the modules the site stops functioning and redirects to core/install.phpF

**To Reproduce**
Following documentation: https://www.drupal.org/docs/8/modules/apigee-api-catalog/expose-rest-apis-to-interact-with-api-docs#install-patch-and-module

**Version Info**
Seen on latest- 
8.x-1.8

**Comment by arlina-espinoza** [comment]
Confirmed that the second patch from the instructions (`"JSON:API call to a member function getTypeName() on boolean":
"https://www.drupal.org/files/issues/2019-05-29/3034786-36.patch"`) isn't needed on Drupal 8.8.x, as the fix was committed. It is only needed if running core 8.7.x. 

Related: https://www.drupal.org/project/drupal/issues/3034786

**Comment by giteshk** [comment]
@arlina-espinoza I found out that this was happening because of [this issue](https://www.drupal.org/project/jsonapi/issues/3059472#new)

I updated the [docs page](https://www.drupal.org/docs/8/modules/apigee-api-catalog/expose-rest-apis-to-interact-with-api-docs) to include the need to set the **max_allowed_packet** variable to **64M** or higher in my.cnf file

Additionally we simplified the steps by utilizing a [patch](https://www.drupal.org/project/jsonapi_extras/issues/2896799#comment-13602720) created for jsonapi_extras module to take the changes from jsonapi_extras_bulk to jsonapi_extras
